### ISSUE TITLE
Make columns on transaction page sortable

### ISSUE THREAD

**Issue by nielslange** [limikael/wp-seeds#12]

**Comment by limikael** [comment]
:+1: yes

**Comment by nielslange** [comment]
I've seen that the seed functionality isn't based on CPTs ([Custom Post Types](https://wordpress.org/support/article/post-types/#custom-post-types)) which makes it rather hard to make columns sortable. I suggest that we change the underlying architecture of the plugin so that we can use all the benefits of CPTs.

How does that sound to you, @limikael, and shall we get started already or shall we do that together once I'm back in Ubud in October? I arrived back in Germany earlier today and despite the timezone difference we could implement the CPT-based solution together using one of the may available pair programing tools, e.g. the ones listed on https://www.sitepoint.com/collaborative-coding-tools-for-remote-pair-programming/.

**Comment by limikael** [comment]
Interesting idea! I'm open to it... I'm aware of the CPT architecture in Wordpress, let me think what the reason was for not using it in the beginning. I think I just thought that a transaction wasn't one of those thinngs that was supposed to be a post. But that's not a very rational reason. Let me map out the pros and cons for mysef:

Cons:

* Performance overhead since there might be many transactions on a site. But to make this more rational... Is WordPress optimized for this? If there are 1000 items belonging to a CPT, will this slow down the performance of the standard posts and pages?
* Security stuff... If it is just a database table, I feel more in control and know what is going on..

Pros:

* Follows a standard WordPress pattern which makes it easier to collaborate with others.

And that "pro" alone might actually make it worth it... :)

What would you say about creating a branch and implementing something there? And then we can compare the different implementations later?

**Comment by nielslange** [comment]
> Performance overhead since there might be many transactions on a site. But to make this more rational... Is WordPress optimized for this? If there are 1000 items belonging to a CPT, will this slow down the performance of the standard posts and pages?

CPTs will have no significant impact on performance. Of course, if 1 million posts belong to a CPT, the site might load a bit slower than usual. However, if you're not using CPTs and still have 1 million items in the database, your site speed would still be affected. Thus, it's more a question of what you store and how the data is handled rather than if the functionality is implemented using CPTs. 

> What would you say about creating a branch and implementing something there? And then we can compare the different implementations later?

Sounds like a great plan!

**Comment by limikael** [comment]
Sounds good! Just go ahead and hack... :) I created a new branch:

https://github.com/limikael/wp-seeds/tree/cpt

So either do it there... Or if it feels easier to start clean, do it as a new repo and we can merge it manually later...

**Comment by nielslange** [comment]
Close issue as this had been implemented in https://github.com/limikael/wp-seeds/pull/39.
